test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./load/gt/valid/full
  wrapper:
    name: sr-implicit-downsampled
    args:
      scale_min: 8
  batch_size: 1
eval_type:
eval_bsize: 30000

data_norm:
  inp: {sub: [0], div: [1]}
  gt: {sub: [0], div: [1]}