train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/dataset/X4_detail_bmp_train
      root_path_2: ./load/dataset/Gt_detail_bmp_train
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-paired
    args:
      inp_size: 48
      augment: true
  batch_size: 16

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/dataset/X4_detail_bmp_valid
      root_path_2: ./load/dataset/Gt_detail_bmp_valid
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-paired
    args:
      inp_size: 48
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        scale: 4

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100
